version: '3.4'

services:
  gamefindermain:
    image: gamefindermain
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTRES_DATABASE: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432

    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
volumes:
  postgres_data: