version: '3.8'
services:
  web:
    build: .
    command: python ./gameFinder/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/gameFinder
    ports:
      - 8000:8000
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: