# Generated by Django 4.0.10 on 2023-05-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamefinder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developingcompany',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='user_id',
            new_name='user',
        ),
    ]
