# Generated by Django 4.0.10 on 2023-05-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamefinder', '0002_rename_user_id_developingcompany_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developingcompany',
            name='user',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='user',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='user',
        ),
    ]
