version: '3.10'

services:
  gamefinder:
    image: gamefinder
    command: "python manage.py migrate"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data1
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
