version: '3.4'

services:
  gamefinder:
    image: gamefinder
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgres
    environment:
      POSTGRES_DB: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432

volumes:
  postgres_data:
